version: lokal/v1alpha1
kind: Workspace
name: foo
namespace: foo
helmReleases:
  - name: redis
    spec:
      repo: https://charts.bitnami.com/bitnami
      version: 16.8.5
      remoteChart: redis
      valuesFiles:
        - ./charts/redis/values.yaml
  - name: mongodb
    spec:
      chartPath: ./charts/mongodb

apps:
  - name: service1
    lokalFile: ".lokal"
    portForward: 3000
    spec:
      env:
        FOO: "workspaceFoo"
      repository:
        localPath: "./apps/service1"
        repoUrl: "git@github.com:vargaadam/example-service.git"
        branch: "dev"
  - name: service2
    portForward: 3001
    spec:
      repository:
        localPath: "./apps/service2"
        repoUrl: "git@github.com:vargaadam/example-service.git"
